/**
 * Maps TIERS company names → Yahoo Finance ticker symbols.
 * Private companies are intentionally omitted.
 * International tickers use Yahoo's exchange suffix format (e.g. 4063.T = Tokyo).
 */
export const TICKERS: Record<string, string> = {
  // ── T1 · Fabless Designers ──────────────────────────────────────────────
  "Nvidia":                    "NVDA",
  "AMD":                       "AMD",
  "Apple":                     "AAPL",
  "Qualcomm":                  "QCOM",
  "Broadcom":                  "AVGO",
  "MediaTek":                  "2454.TW",
  "Marvell Technology":        "MRVL",
  "Amazon Web Services":       "AMZN",
  "Google":                    "GOOGL",
  "Microsoft":                 "MSFT",
  "Meta Platforms":            "META",
  "Tesla":                     "TSLA",
  "Cisco Systems":             "CSCO",
  "IBM":                       "IBM",
  "Realtek Semiconductor":     "2379.TW",
  "Novatek Microelectronics":  "3034.TW",
  "Cirrus Logic":              "CRUS",
  "Skyworks Solutions":        "SWKS",
  "Qorvo":                     "QRVO",
  "Monolithic Power Systems":  "MPWR",
  "Ambarella":                 "AMBA",
  "Lattice Semiconductor":     "LSCC",
  "Synaptics":                 "SYNA",
  "Wolfspeed":                 "WOLF",
  "Nordic Semiconductor":      "NOD.OL",
  "Macom Technology Solutions":"MTSI",
  "Semtech":                   "SMTC",
  "MaxLinear":                 "MXL",
  "Allegro MicroSystems":      "ALGM",
  "Rambus":                    "RMBS",
  "CEVA":                      "CEVA",
  "Silicon Laboratories":      "SLAB",
  "Himax Technologies":        "HIMX",
  "BrainChip":                 "BRN.AX",

  // ── T2 · Foundries, IDMs & OSATs ────────────────────────────────────────
  "TSMC":                      "TSM",
  "Samsung Foundry":           "005930.KS",
  "Intel Foundry":             "INTC",
  "SK Hynix":                  "000660.KS",
  "Micron Technology":         "MU",
  "GlobalFoundries":           "GFS",
  "UMC":                       "UMC",
  "Texas Instruments":         "TXN",
  "STMicroelectronics":        "STM",
  "Infineon Technologies":     "IFX.DE",
  "NXP Semiconductors":        "NXPI",
  "Analog Devices":            "ADI",
  "Renesas Electronics":       "6723.T",
  "Microchip Technology":      "MCHP",
  "onsemi":                    "ON",
  "Kioxia":                    "285A.T",
  "Tower Semiconductor":       "TSEM",
  "ASE Group":                 "ASX",
  "Amkor Technology":          "AMKR",
  "Rohm Semiconductor":        "6963.T",
  "SkyWater Technology":       "SKYT",
  "X-Fab":                     "XFAB.PA",

  // ── T3 · Equipment ──────────────────────────────────────────────────────
  "ASML":                      "ASML",
  "Applied Materials":         "AMAT",
  "Lam Research":              "LRCX",
  "KLA Corporation":           "KLAC",
  "Nikon Corporation":         "7731.T",
  "Canon Inc.":                "CAJ",
  "ASM International":         "ASMIY",
  "Advantest":                 "ATEYY",
  "Teradyne":                  "TER",
  "Onto Innovation":           "ONTO",
  "Veeco Instruments":         "VECO",
  "BE Semiconductor Industries":"BESI.AS",
  "Kulicke & Soffa":           "KLIC",
  "Axcelis Technologies":      "ACLS",
  "FormFactor":                "FORM",
  "Cohu":                      "COHU",
  "Camtek":                    "CAMT",
  "Nordson Corporation":       "NDSN",
  "IPG Photonics":             "IPGP",
  "ACM Research":              "ACMR",

  // ── T4 · Subsystems ─────────────────────────────────────────────────────
  "MKS Instruments":           "MKSI",
  "Advanced Energy":           "AEIS",
  "Coherent":                  "COHR",
  "Parker Hannifin":           "PH",
  "Ultra Clean Holdings":      "UCTT",
  "Ichor Systems":             "ICHR",
  "Moog Inc.":                 "MOG.A",
  "Yaskawa Electric":          "6506.T",
  "Fanuc":                     "6954.T",
  "SKF Group":                 "SKF-B.ST",
  "XP Power":                  "XPP.L",
  "Pfeiffer Vacuum":           "PFV.DE",
  "Ebara Corporation":         "6361.T",

  // ── T5 · Components ─────────────────────────────────────────────────────
  "Corning Inc.":              "GLW",
  "Hoya Corporation":          "7741.T",
  "Kyocera Corporation":       "6971.T",
  "Renishaw":                  "RSW.L",
  "Materion":                  "MTRN",
  "Hirose Electric":           "6806.T",
  "Huber+Suhner":              "HUBN.SW",
  "TDK-Lambda":                "6762.T",

  // ── T6 · Materials ──────────────────────────────────────────────────────
  "Shin-Etsu Chemical":        "4063.T",
  "Sumco Corporation":         "3436.T",
  "Siltronic AG":              "WAF.DE",
  "DuPont Electronic Solutions":"DD",
  "Merck KGaA":                "MRK.DE",
  "Linde plc":                 "LIN",
  "Air Liquide":               "AI.PA",
  "Sumitomo Chemical":         "4005.T",
  "BASF Electronic Materials": "BAS.DE",
  "Umicore":                   "UMI.BR",
  "Honeywell Electronic Materials":"HON",
  "AT&S":                      "ATS.VI",
  "Nitto Denko":               "6988.T",
  "Air Products and Chemicals":"APD",
  "Arkema":                    "AKE.PA",
  "Solvay":                    "SOLVY",
  "Dexerials Corporation":     "4980.T",
  "Adeka Corporation":         "4401.T",

  // ── T7 · Mining & Extraction ────────────────────────────────────────────
  "Wacker Chemie":             "WCH.DE",
  "OCI Company":               "010060.KS",
  "REC Silicon":               "RECSI.OL",
  "Daqo New Energy":           "DQ",
  "Lynas Rare Earths":         "LYC.AX",
  "MP Materials":              "MP",
  "Iluka Resources":           "ILU.AX",
  "Tronox":                    "TROX",
  "Rio Tinto":                 "RIO",
  "BHP Group":                 "BHP",
  "Freeport-McMoRan":          "FCX",
  "Antofagasta plc":           "ANTO.L",
  "Southern Copper Corporation":"SCCO",
  "Anglo American":            "AAL.L",
  "Vale S.A.":                 "VALE",
  "Alcoa Corporation":         "AA",
  "Norsk Hydro":               "NHY.OL",
  "Albemarle Corporation":     "ALB",
  "SQM":                       "SQM",
  "Dow Chemical":              "DOW",
  "Chemours":                  "CC",
  "Asahi Kasei":               "3407.T",
  "Tosoh Corporation":         "4042.T",
  "Mitsui Chemicals":          "4183.T",
}