export type Company = [name: string, countryCode: string, url: string]

export interface Tier {
  level: number
  name: string
  tag: string
  color: string
  cbg: string
  cbr: string
  desc: string
  cos: Company[]
}

export const TIERS: Tier[] = [
  {
    level: 1,
    name: "Fabless Designers & Tech Architects",
    tag: "The Brains — Design without factories",
    color: "#00d4ff",
    cbg: "rgba(0,212,255,0.08)",
    cbr: "rgba(0,212,255,0.28)",
    desc: "These companies do not own chip factories. They design the architecture, logic, and instruction sets for semiconductors, or buy them at enterprise scale to build consumer electronics and cloud servers.",
    cos: [
      ["Nvidia", "US", "https://www.nvidia.com"],
      ["AMD", "US", "https://www.amd.com"],
      ["Apple", "US", "https://www.apple.com"],
      ["Qualcomm", "US", "https://www.qualcomm.com"],
      ["Broadcom", "US", "https://www.broadcom.com"],
      ["MediaTek", "TW", "https://www.mediatek.com"],
      ["Marvell Technology", "US", "https://www.marvell.com"],
      ["Amazon Web Services", "US", "https://aws.amazon.com"],
      ["Google", "US", "https://about.google"],
      ["Microsoft", "US", "https://www.microsoft.com"],
      ["Meta Platforms", "US", "https://about.meta.com"],
      ["Tesla", "US", "https://www.tesla.com"],
      ["Cisco Systems", "US", "https://www.cisco.com"],
      ["IBM", "US", "https://www.ibm.com"],
      ["Realtek Semiconductor", "TW", "https://www.realtek.com"],
      ["Novatek Microelectronics", "TW", "https://www.novatek.com.tw"],
      ["Cirrus Logic", "US", "https://www.cirrus.com"],
      ["Skyworks Solutions", "US", "https://www.skyworksinc.com"],
      ["Qorvo", "US", "https://www.qorvo.com"],
      ["Monolithic Power Systems", "US", "https://www.monolithicpower.com"],
      ["Ambarella", "US", "https://www.ambarella.com"],
      ["Lattice Semiconductor", "US", "https://www.latticesemi.com"],
      ["Altera", "US", "https://www.altera.com"],
      ["Synaptics", "US", "https://www.synaptics.com"],
      ["Wolfspeed", "US", "https://www.wolfspeed.com"],
      ["Nordic Semiconductor", "NO", "https://www.nordicsemi.com"],
      ["Macom Technology Solutions", "US", "https://www.macom.com"],
      ["Semtech", "US", "https://www.semtech.com"],
      ["MaxLinear", "US", "https://www.maxlinear.com"],
      ["Allegro MicroSystems", "US", "https://www.allegromicro.com"],
      ["Rambus", "US", "https://www.rambus.com"],
      ["CEVA", "US", "https://www.ceva-dsp.com"],
      ["Silicon Laboratories", "US", "https://www.silabs.com"],
      ["OmniVision Technologies", "US", "https://www.ovt.com"],
      ["Himax Technologies", "TW", "https://www.himax.com.tw"],
      ["Unisoc", "CN", "https://www.unisoc.com"],
      ["HiSilicon", "CN", "https://www.hisilicon.com"],
      ["Graphcore", "UK", "https://www.graphcore.ai"],
      ["Tenstorrent", "CA", "https://tenstorrent.com"],
      ["Cerebras Systems", "US", "https://www.cerebras.net"],
      ["SambaNova Systems", "US", "https://sambanova.ai"],
      ["Groq", "US", "https://groq.com"],
      ["SiFive", "US", "https://www.sifive.com"],
      ["Enfusion", "US", "https://www.enfusion.com"],
      ["Syntiant", "US", "https://www.syntiant.com"],
      ["Esperanto Technologies", "US", "https://www.esperanto.ai"],
      ["Hailo", "IL", "https://hailo.ai"],
      ["Untether AI", "CA", "https://www.untether.ai"],
      ["BrainChip", "AU", "https://brainchip.com"],
      ["Mythic", "US", "https://www.mythic-ai.com"],
    ],
  },
  {
    level: 2,
    name: "Foundries, IDMs, & OSATs",
    tag: "The Fabs & Assembly — Physical manufacturing",
    color: "#4a9eff",
    cbg: "rgba(74,158,255,0.08)",
    cbr: "rgba(74,158,255,0.28)",
    desc: "Integrated Device Manufacturers (IDMs) design and make their own chips. Pure-play foundries build chips for others. OSATs handle advanced packaging, dicing, and testing of finished dies.",
    cos: [
      ["TSMC", "TW", "https://www.tsmc.com"],
      ["Samsung Foundry", "KR", "https://www.samsung.com/semiconductor"],
      ["Intel Foundry", "US", "https://www.intel.com/foundry"],
      ["SK Hynix", "KR", "https://www.skhynix.com"],
      ["Micron Technology", "US", "https://www.micron.com"],
      ["GlobalFoundries", "US", "https://gf.com"],
      ["UMC", "TW", "https://www.umc.com"],
      ["SMIC", "CN", "https://www.smics.com"],
      ["Texas Instruments", "US", "https://www.ti.com"],
      ["STMicroelectronics", "CH", "https://www.st.com"],
      ["Infineon Technologies", "DE", "https://www.infineon.com"],
      ["NXP Semiconductors", "NL", "https://www.nxp.com"],
      ["Analog Devices", "US", "https://www.analog.com"],
      ["Renesas Electronics", "JP", "https://www.renesas.com"],
      ["Microchip Technology", "US", "https://www.microchip.com"],
      ["onsemi", "US", "https://www.onsemi.com"],
      ["Sony Semiconductor Solutions", "JP", "https://www.sony-semicon.com"],
      ["Kioxia", "JP", "https://www.kioxia.com"],
      ["Tower Semiconductor", "IL", "https://www.towersemi.com"],
      ["VIS", "TW", "https://www.vis.com.tw"],
      ["Hua Hong Semiconductor", "CN", "https://www.huahonggrace.com"],
      ["ASE Group", "TW", "https://www.aseglobal.com"],
      ["Amkor Technology", "US", "https://www.amkor.com"],
      ["JCET Group", "CN", "https://www.jcetglobal.com"],
      ["Powertech Technology", "TW", "https://www.ptitw.com"],
      ["SPIL", "TW", "https://www.spil.com.tw"],
      ["King Yuan Electronics", "TW", "https://www.kyec.com.tw"],
      ["TFME", "CN", "https://www.tfme.com"],
      ["Tianshui Huatian Technology", "CN", "https://www.huatian.com"],
      ["UTAC Group", "SG", "https://www.utacgroup.com"],
      ["ChipMOS Technologies", "TW", "https://www.chipmos.com"],
      ["Chipbond Technology", "TW", "https://www.chipbond.com.tw"],
      ["Signetics", "KR", "https://www.signetics.co.kr"],
      ["Hana Micron", "KR", "https://www.hanamicron.com"],
      ["SFA Semicon", "KR", "https://www.sfasemicon.com"],
      ["Win Semiconductors", "TW", "https://www.winfoundry.com"],
      ["AWSC", "TW", "https://www.awsc.com.tw"],
      ["DB Hitek", "KR", "https://www.dbhitek.com"],
      ["Nexchip", "CN", "https://www.nexchip.com"],
      ["Fujitsu Semiconductor", "JP", "https://www.fujitsu.com/global/products/devices/"],
      ["Toshiba Electronic Devices", "JP", "https://toshiba.semicon-storage.com"],
      ["Rohm Semiconductor", "JP", "https://www.rohm.com"],
      ["SkyWater Technology", "US", "https://www.skywatertechnology.com"],
      ["JS Foundry", "JP", "https://www.j-found.co.jp"],
      ["Bosch Semiconductors", "DE", "https://www.bosch-semiconductors.com"],
      ["SanAn IC", "CN", "https://www.sanan-ic.com"],
      ["X-Fab", "DE", "https://www.xfab.com"],
      ["United Power Research", "TW", "https://www.upr.com.tw"],
      ["Greatek Electronics", "TW", "https://www.greatek.com.tw"],
      ["Lingsen Precision Industries", "TW", "https://www.lingsen.com.tw"],
    ],
  },
  {
    level: 3,
    name: "Semiconductor Manufacturing Equipment (SME) Integrators",
    tag: "The Machines — Cleanroom toolmakers",
    color: "#9b7cff",
    cbg: "rgba(155,124,255,0.08)",
    cbr: "rgba(155,124,255,0.28)",
    desc: "These companies build the physical, room-sized machines that populate cleanrooms: tools for lithography, thin-film deposition, chemical mechanical planarization, plasma etching, and diagnostic wafer inspection.",
    cos: [
      ["ASML", "NL", "https://www.asml.com"],
      ["Applied Materials", "US", "https://www.appliedmaterials.com"],
      ["Lam Research", "US", "https://www.lamresearch.com"],
      ["Tokyo Electron", "JP", "https://www.tel.com"],
      ["KLA Corporation", "US", "https://www.kla.com"],
      ["Nikon Corporation", "JP", "https://www.nikon.com"],
      ["Canon Inc.", "JP", "https://www.canon.com"],
      ["Screen Holdings", "JP", "https://www.screen.co.jp"],
      ["ASM International", "NL", "https://www.asm.com"],
      ["Hitachi High-Tech", "JP", "https://www.hitachi-hightech.com"],
      ["Advantest", "JP", "https://www.advantest.com"],
      ["Teradyne", "US", "https://www.teradyne.com"],
      ["Kokusai Electric", "JP", "https://www.kokusai-electric.com"],
      ["Onto Innovation", "US", "https://www.ontoinnovation.com"],
      ["Veeco Instruments", "US", "https://www.veeco.com"],
      ["EV Group", "AT", "https://www.evgroup.com"],
      ["BE Semiconductor Industries", "NL", "https://www.besi.com"],
      ["Plasma-Therm", "US", "https://www.plasmatherm.com"],
      ["Kulicke & Soffa", "SG", "https://www.kns.com"],
      ["Suss MicroTec", "DE", "https://www.suss.com"],
      ["Daifuku", "JP", "https://www.daifuku.com"],
      ["Murata Machinery", "JP", "https://www.muratec.com"],
      ["Shinkawa", "JP", "https://www.shinkawa.com"],
      ["ASM Pacific Technology", "SG", "https://www.asmpacific.com"],
      ["Towa Corporation", "JP", "https://www.towa.co.jp"],
      ["Disco Corporation", "JP", "https://www.disco.co.jp"],
      ["Tokyo Seimitsu", "JP", "https://www.accretech.com"],
      ["Okamoto Machine Tool Works", "JP", "https://www.okamoto-grinder.com"],
      ["Semes", "KR", "https://www.semes.com"],
      ["Wonik IPS", "KR", "https://www.wonikips.com"],
      ["Eugene Technology", "KR", "https://www.eugenetech.co.kr"],
      ["Hanmi Semiconductor", "KR", "https://www.hanmisemiconductor.com"],
      ["JUSUNG Engineering", "KR", "https://www.jusung.com"],
      ["Naura Technology Group", "CN", "https://www.naura.com"],
      ["AMEC", "CN", "https://www.amec-ma.com"],
      ["Piotech", "CN", "https://www.piotech.com"],
      ["Kingsemi", "CN", "https://www.kingsemi.com"],
      ["ACM Research", "US", "https://www.acmrcsh.com"],
      ["JEOL Ltd.", "JP", "https://www.jeol.com"],
      ["Park Systems", "KR", "https://www.parksystems.com"],
      ["FormFactor", "US", "https://www.formfactor.com"],
      ["Technoprobe", "IT", "https://www.technoprobe.com"],
      ["Cohu", "US", "https://www.cohu.com"],
      ["Camtek", "IL", "https://www.camtek.com"],
      ["Nordson Corporation", "US", "https://www.nordson.com"],
      ["IPG Photonics", "US", "https://www.ipgphotonics.com"],
      ["Mattson Technology", "US", "https://www.mattson.com"],
      ["Axcelis Technologies", "US", "https://www.axcelis.com"],
      ["Amtech Systems", "US", "https://www.amtechsystems.com"],
      ["Nova Measuring Instruments", "IL", "https://www.novami.com"],
    ],
  },
  {
    level: 4,
    name: "Tier-1 Equipment Subsystems & Modules",
    tag: "The Organs — Vital internal components",
    color: "#c77dff",
    cbg: "rgba(199,125,255,0.08)",
    cbr: "rgba(199,125,255,0.28)",
    desc: "These engineering firms build the vital organs inside Level 3 machines: lasers, optical blocks, vacuum lines, gas delivery systems, and precision robotic units. Without these sub-assemblies, lithography and etching tools cannot operate.",
    cos: [
      ["Carl Zeiss SMT", "DE", "https://www.zeiss.com/semiconductor-manufacturing-technology"],
      ["TRUMPF", "DE", "https://www.trumpf.com"],
      ["VDL Groep", "NL", "https://www.vdlgroep.com"],
      ["MKS Instruments", "US", "https://www.mks.com"],
      ["Advanced Energy", "US", "https://www.advancedenergy.com"],
      ["Horiba", "JP", "https://www.horiba.com"],
      ["Brooks Automation", "US", "https://www.brooks.com"],
      ["Cymer", "US", "https://www.cymer.com"],
      ["Gigaphoton", "JP", "https://www.gigaphoton.com"],
      ["Entegris", "US", "https://www.entegris.com"],
      ["Comet Group", "CH", "https://www.comet-group.com"],
      ["Ushio", "JP", "https://www.ushio.co.jp"],
      ["Coherent", "US", "https://www.coherent.com"],
      ["Energetiq Technology", "US", "https://www.energetiq.com"],
      ["Newport Corporation", "US", "https://www.newport.com"],
      ["Excelitas Technologies", "US", "https://www.excelitas.com"],
      ["Jenoptik", "DE", "https://www.jenoptik.com"],
      ["Leybold", "DE", "https://www.leybold.com"],
      ["Kashiyama Industries", "JP", "https://www.kashiyama.co.jp"],
      ["Kinetics Fluid Systems", "US", "https://www.kineticssystems.com"],
      ["Ultra Clean Holdings", "US", "https://www.uct.com"],
      ["Ichor Systems", "US", "https://www.ichorsystems.com"],
      ["Swagelok", "US", "https://www.swagelok.com"],
      ["Parker Hannifin", "US", "https://www.parker.com"],
      ["SMC Corporation", "JP", "https://www.smcworld.com"],
      ["Festo", "DE", "https://www.festo.com"],
      ["CKD Corporation", "JP", "https://www.ckd.co.jp"],
      ["Moog Inc.", "US", "https://www.moog.com"],
      ["Yaskawa Electric", "JP", "https://www.yaskawa.com"],
      ["Fanuc", "JP", "https://www.fanuc.com"],
      ["Harmonic Drive Systems", "JP", "https://www.harmonicdrive.net"],
      ["Nabtesco Corporation", "JP", "https://www.nabtesco.com"],
      ["THK Co. Ltd.", "JP", "https://www.thk.com"],
      ["NSK Ltd.", "JP", "https://www.nsk.com"],
      ["NTN Corporation", "JP", "https://www.ntn.co.jp"],
      ["SKF Group", "SE", "https://www.skf.com"],
      ["Kyosan Electric", "JP", "https://www.kyosan.co.jp"],
      ["Daihen Corporation", "JP", "https://www.daihen.co.jp"],
      ["Spellman High Voltage", "US", "https://www.spellmanhv.com"],
      ["XP Power", "UK", "https://www.xppower.com"],
      ["Bürkert Fluid Control", "DE", "https://www.burkert.com"],
      ["Bronkhorst High-Tech", "NL", "https://www.bronkhorst.com"],
      ["Aalborg Instruments", "US", "https://www.aalborg.com"],
      ["Teledyne Hastings", "US", "https://www.teledynehastings.com"],
      ["Inficon", "CH", "https://www.inficon.com"],
      ["Hiden Analytical", "UK", "https://www.hidenanalytical.com"],
      ["Edwards Vacuum", "UK", "https://www.edwardsvacuum.com"],
      ["VAT Vacuum Valves", "CH", "https://www.vatvalve.com"],
      ["Pfeiffer Vacuum", "DE", "https://www.pfeiffer-vacuum.com"],
      ["Ebara Corporation", "JP", "https://www.ebara.com"],
    ],
  },
  {
    level: 5,
    name: "Tier-2 Precision Components & Opto-Mechatronics",
    tag: "The Cells — Raw mechanical & optical elements",
    color: "#00e0a0",
    cbg: "rgba(0,224,160,0.08)",
    cbr: "rgba(0,224,160,0.28)",
    desc: "These companies manufacture the raw mechanical components, specialized structural glass, positioning units, and electronics required by Level 4 subsystem creators — including mirror substrates, piezoelectric stages, optical encoders, and specialty elastomer seals.",
    cos: [
      ["Schott AG", "DE", "https://www.schott.com"],
      ["Corning Inc.", "US", "https://www.corning.com"],
      ["Hoya Corporation", "JP", "https://www.hoya.com"],
      ["Berliner Glas", "DE", "https://www.berlinerglas.com"],
      ["NTS-Group", "NL", "https://www.nts-group.nl"],
      ["Frencken Group", "NL", "https://www.frenckengroup.com"],
      ["Prodrive Technologies", "NL", "https://www.prodrive.com"],
      ["Access Laser", "US", "https://www.accesslaser.com"],
      ["AMPHOS", "DE", "https://www.amphos.de"],
      ["PI Physik Instrumente", "DE", "https://www.pi.ws"],
      ["Heidenhain", "DE", "https://www.heidenhain.com"],
      ["Renishaw", "UK", "https://www.renishaw.com"],
      ["Kyocera Corporation", "JP", "https://www.kyocera.com"],
      ["CoorsTek", "US", "https://www.coorstek.com"],
      ["FerroTec", "JP", "https://www.ferrotec.com"],
      ["PM Group", "NL", "https://www.pmgroup-global.com"],
      ["KMWE", "NL", "https://www.kmwe.com"],
      ["AAE bv", "NL", "https://www.aae.nl"],
      ["Neways Electronics", "NL", "https://www.neways.com"],
      ["AGC Inc.", "JP", "https://www.agc.com"],
      ["Tosoh Quartz", "JP", "https://www.tosohquartz.com"],
      ["Heraeus Conamic", "DE", "https://www.heraeus.com"],
      ["Shin-Etsu Quartz", "JP", "https://www.squartz.co.jp"],
      ["Saint-Gobain Performance Plastics", "FR", "https://www.saint-gobain.com"],
      ["Greene Tweed", "US", "https://www.greentweed.com"],
      ["DuPont Kalrez", "US", "https://www.dupont.com"],
      ["Parker Hannifin Parofluor", "US", "https://www.parker.com"],
      ["Techno Semi", "JP", "https://www.technosemi.co.jp"],
      ["Miyha", "JP", "https://www.miyha.co.jp"],
      ["Edmund Optics", "US", "https://www.edmundoptics.com"],
      ["Thorlabs", "US", "https://www.thorlabs.com"],
      ["Newport Optics", "US", "https://www.newport.com"],
      ["Materion", "US", "https://www.materion.com"],
      ["Ophir Optronics", "IL", "https://www.ophiropt.com"],
      ["Mitutoyo", "JP", "https://www.mitutoyo.com"],
      ["Magnescale", "JP", "https://www.magnescale.com"],
      ["Tamagawa Seiki", "JP", "https://www.tamagawa-seiki.com"],
      ["Kugler GmbH", "DE", "https://www.kugler-precision.com"],
      ["Aerotech Inc.", "US", "https://www.aerotech.com"],
      ["Dover Motion", "US", "https://www.dovermotionsolutions.com"],
      ["Celera Motion", "US", "https://www.celeramotion.com"],
      ["Maxon Motor", "CH", "https://www.maxongroup.com"],
      ["Faulhaber", "DE", "https://www.faulhaber.com"],
      ["Oriental Motor", "JP", "https://www.orientalmotor.com"],
      ["Tamagawa Electronics", "JP", "https://www.tamagawa.co.jp"],
      ["Huber+Suhner", "CH", "https://www.hubersuhner.com"],
      ["Rosenberger", "DE", "https://www.rosenberger.com"],
      ["Hirose Electric", "JP", "https://www.hirose.com"],
      ["Samtec", "US", "https://www.samtec.com"],
      ["TDK-Lambda", "JP", "https://www.tdk-lambda.com"],
    ],
  },
  {
    level: 6,
    name: "High-Purity Process Materials, Gases, & Substrates",
    tag: "The Consumables — What fabs burn through daily",
    color: "#f5a623",
    cbg: "rgba(245,166,35,0.08)",
    cbr: "rgba(245,166,35,0.28)",
    desc: "These chemical and material firms supply the consumable assets that feed Level 2 fabs: raw silicon wafers, light-sensitive photoresists, polishing slurries, advanced packaging substrates, and specialty process gases.",
    cos: [
      ["Shin-Etsu Chemical", "JP", "https://www.shinetsu.co.jp"],
      ["Sumco Corporation", "JP", "https://www.sumcosi.com"],
      ["Siltronic AG", "DE", "https://www.siltronic.com"],
      ["GlobalWafers", "TW", "https://www.globalwafers.com.tw"],
      ["SK Siltron", "KR", "https://www.sksiltron.com"],
      ["JSR Corporation", "JP", "https://www.jsr.co.jp"],
      ["Tokyo Ohka Kogyo", "JP", "https://www.tok.co.jp"],
      ["DuPont Electronic Solutions", "US", "https://www.dupont.com/electronics-industrial.html"],
      ["Merck KGaA", "DE", "https://www.merckgroup.com"],
      ["Fujifilm Electronic Materials", "JP", "https://www.fujifilm.com/ffem"],
      ["Sumitomo Chemical", "JP", "https://www.sumitomo-chem.co.jp"],
      ["Linde plc", "UK", "https://www.linde.com"],
      ["Air Liquide", "FR", "https://www.airliquide.com"],
      ["Taiyo Nippon Sanso", "JP", "https://www.tn-sanso.co.jp"],
      ["Resonac", "JP", "https://www.resonac.com"],
      ["BASF Electronic Materials", "DE", "https://www.basf.com"],
      ["Umicore", "BE", "https://www.umicore.com"],
      ["JX Nippon Mining & Metals", "JP", "https://www.jx-nmm.co.jp"],
      ["Honeywell Electronic Materials", "US", "https://www.honeywell.com"],
      ["Shinko Electric Industries", "JP", "https://www.shinko-elec.co.jp"],
      ["Ibiden Co. Ltd.", "JP", "https://www.ibiden.com"],
      ["Unimicron Technology", "TW", "https://www.unimicron.com"],
      ["Nan Ya PCB", "TW", "https://www.nanyapcb.com.tw"],
      ["Kinsus Interconnect Technology", "TW", "https://www.kinsus.com.tw"],
      ["AT&S", "AT", "https://www.ats.net"],
      ["Ajinomoto Fine-Techno", "JP", "https://www.ajinomoto-fine-techno.co.jp"],
      ["Kanto Chemical", "JP", "https://www.kanto.co.jp"],
      ["Chang Chun Petrochemical", "TW", "https://www.ccp.com.tw"],
      ["SoulBrain", "KR", "https://www.soulbrain.co.kr"],
      ["Dongjin Semichem", "KR", "https://www.dongjin.com"],
      ["Adeka Corporation", "JP", "https://www.adeka.co.jp"],
      ["Air Products and Chemicals", "US", "https://www.airproducts.com"],
      ["Matheson Tri-Gas", "US", "https://www.mathesongas.com"],
      ["SK Materials", "KR", "https://www.skmaterials.co.kr"],
      ["Peric Special Gases", "CN", "https://www.pericgas.com"],
      ["Huate Gas", "CN", "https://www.huategas.com"],
      ["Nata Optoelectronic", "CN", "https://www.nata-opto.com"],
      ["Messer Group", "DE", "https://www.messergroup.com"],
      ["Solvay", "BE", "https://www.solvay.com"],
      ["Arkema", "FR", "https://www.arkema.com"],
      ["MacDermid Alpha Electronics", "US", "https://www.macdermidalpha.com"],
      ["Tanaka Precious Metals", "JP", "https://www.tanaka.co.jp"],
      ["Heraeus Electronics", "DE", "https://www.heraeus.com"],
      ["Tatsuta Electric Wire & Cable", "JP", "https://www.tatsuta.co.jp"],
      ["Nitto Denko", "JP", "https://www.nitto.com"],
      ["Lintec Corporation", "JP", "https://www.lintec.co.jp"],
      ["Sekisui Chemical", "JP", "https://www.sekisui.co.jp"],
      ["Namics Corporation", "JP", "https://www.namics.com"],
      ["Dexerials Corporation", "JP", "https://www.dexerials.jp"],
      ["Henkel Electronic Materials", "DE", "https://www.henkel.com"],
    ],
  },
  {
    level: 7,
    name: "Commodity Extraction, Metallurgical Refining, & Precursors",
    tag: "The Earth — Mines, minerals, and raw chemistry",
    color: "#ff6b35",
    cbg: "rgba(255,107,53,0.08)",
    cbr: "rgba(255,107,53,0.28)",
    desc: "The absolute bedrock tier. These entities handle raw mining of earth minerals, chemical cracking, and elementary processing that feed the Level 6 chemical formulation companies. Without these, no silicon wafer can be grown.",
    cos: [
      ["Sibelco", "BE", "https://www.sibelco.com"],
      ["The Quartz Corp", "NO", "https://www.thequartzcorp.com"],
      ["Wacker Chemie", "DE", "https://www.wacker.com"],
      ["OCI Company", "KR", "https://www.oci.co.kr"],
      ["Hemlock Semiconductor", "US", "https://www.hscpoly.com"],
      ["Tokuyama Corporation", "JP", "https://www.tokuyama.co.jp"],
      ["REC Silicon", "NO", "https://www.recsilicon.com"],
      ["GCL Technology", "CN", "https://www.gcltech.com"],
      ["Tongwei Co.", "CN", "https://www.tongwei.com"],
      ["Daqo New Energy", "CN", "https://www.dqsolar.com"],
      ["Lynas Rare Earths", "AU", "https://www.lynasrareearths.com"],
      ["MP Materials", "US", "https://www.mpmaterials.com"],
      ["China Rare Earth Group", "CN", "https://www.chinarareearth.com"],
      ["Iluka Resources", "AU", "https://www.iluka.com"],
      ["Tronox", "US", "https://www.tronox.com"],
      ["Rio Tinto", "UK", "https://www.riotinto.com"],
      ["BHP Group", "AU", "https://www.bhp.com"],
      ["Freeport-McMoRan", "US", "https://www.fcx.com"],
      ["Antofagasta plc", "CL", "https://www.antofagasta.co.uk"],
      ["Southern Copper Corporation", "US", "https://www.southerncoppercorp.com"],
      ["Glencore", "CH", "https://www.glencore.com"],
      ["Norilsk Nickel", "RU", "https://www.nornickel.com"],
      ["Anglo American", "UK", "https://www.angloamerican.com"],
      ["Vale S.A.", "BR", "https://www.vale.com"],
      ["Alcoa Corporation", "US", "https://www.alcoa.com"],
      ["Rio Tinto Alcan", "CA", "https://www.riotinto.com/en/operations/canada"],
      ["Norsk Hydro", "NO", "https://www.hydro.com"],
      ["Sumitomo Metal Mining", "JP", "https://www.smm.co.jp"],
      ["Mitsubishi Materials", "JP", "https://www.mmc.co.jp"],
      ["Compass Minerals", "US", "https://www.compassminerals.com"],
      ["Albemarle Corporation", "US", "https://www.albemarle.com"],
      ["SQM", "CL", "https://www.sqm.com"],
      ["FMC Corporation", "US", "https://www.fmc.com"],
      ["Dow Chemical", "US", "https://www.dow.com"],
      ["ExxonMobil Chemical", "US", "https://www.exxonmobilchemical.com"],
      ["Shell Chemical", "NL", "https://www.shell.com"],
      ["Sabic", "SA", "https://www.sabic.com"],
      ["Denka Company", "JP", "https://www.denka.co.jp"],
      ["Tokai Carbon", "JP", "https://www.tokaicarbon.co.jp"],
      ["Toyo Tanso", "JP", "https://www.toyotanso.co.jp"],
      ["Showa Denko Carbon", "JP", "https://www.sdk.co.jp"],
      ["Stella Chemifa", "JP", "https://www.stella-chemifa.co.jp"],
      ["Morita Chemical Industries", "JP", "https://www.moritachem.co.jp"],
      ["Solvay Fluor", "DE", "https://www.solvay.com"],
      ["Fluor Corporation", "US", "https://www.fluor.com"],
      ["Chemours", "US", "https://www.chemours.com"],
      ["Asahi Kasei", "JP", "https://www.asahi-kasei.co.jp"],
      ["Tosoh Corporation", "JP", "https://www.tosoh.com"],
      ["Mitsui Chemicals", "JP", "https://www.mitsuichem.co.jp"],
      ["Chevron Phillips Chemical", "US", "https://www.cpchem.com"],
    ],
  },
]

export const TICKER_ITEMS: [company: string, note: string][] = [
  ["TSMC", "N2 Ramp"],
  ["ASML", "High-NA EUV"],
  ["Nvidia", "GB300 Demand"],
  ["SK Hynix", "HBM4 Sampling"],
  ["Carl Zeiss SMT", "Lens Block Lead Times"],
  ["TRUMPF", "EUV Laser Capacity"],
  ["Shin-Etsu Chemical", "Photoresist Supply"],
  ["Ajinomoto Fine-Techno", "ABF Allocation"],
  ["Sibelco", "Spruce Pine Quartz"],
  ["Intel Foundry", "18A Yield"],
  ["Applied Materials", "ALD Backlog"],
  ["Entegris", "Contamination Filters"],
  ["GlobalWafers", "SOI Substrate Supply"],
  ["Lam Research", "Plasma Etch Orders"],
  ["Hanmi Semiconductor", "TC Bonder Demand"],
]
